server:
  port: 6719

spring:
  application:
    name: wanted-pre-onboarding-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8
    username: wanted
    password: wanted719
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true